/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import model.Sale;
import addPro.addPro;
import javax.swing.JOptionPane;
import login.login;
import model.Product;
import java.awt.CardLayout;
import java.awt.Color;
import controller.Controller;
import javax.swing.JCheckBox;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Liêu Vinh Khôi
 */
public class home extends javax.swing.JFrame {

    DefaultTableModel tbModel;
    DefaultTableModel tbModelSale;
    CardLayout cardLayout;
    Controller con = new Controller();
    addPro addForm = new addPro();

    /**
     * Creates new form home
     */ 
    public home() {
        initComponents();
        cardLayout = (CardLayout) contentPanel.getLayout();
        this.setTitle("Craft Beer");
        this.setLocationRelativeTo(null);
        btnDel.setVisible(false);
        txtTotal.setEnabled(false);

        initTable();
        tbPro.setDefaultEditor(Object.class, null);
        tbSale.setDefaultEditor(Object.class, null);
        boolean file = con.loadFile();
        boolean fileSale = con.loadFileSale();
        if (file) {
            fillToTable();
        } else {
            JOptionPane.showConfirmDialog(null, "Nothing to show");
        }
        if (fileSale) {
            fillToTableSale();
        } else {
            JOptionPane.showMessageDialog(null, "Nothing to show Sale");
        }
        con.loadcbPro();
    }

    private void fillToTable() {
        tbModel.setRowCount(0);
        for (Product c : con.proList) {
            Object[] row = new Object[]{c.getId(), c.getName(), c.getPrice(), c.getNation(), c.getDes()};
            tbModel.addRow(row);
        }
    }

    private void fillToTableSale() {
        tbModelSale.setRowCount(0);
        for (Sale s : con.saleList) {
            Object[] row = new Object[]{s.getId(), s.getName(), s.getSnack(), s.getDate(), s.getTotal()};
            tbModelSale.addRow(row);
        }
    }

    private void initTable() {
        String[] columnNames = {"ID", "Name", "Price", "Nation", "Description"};
        String[] columnName = {"ID", "Name", "Snack", "Date", "Total"};
        tbModel = new DefaultTableModel(columnNames, 0);
        tbModelSale = new DefaultTableModel(columnName, 0);
        tbPro.setModel(tbModel);
        tbSale.setModel(tbModelSale);
    }

    private void filter(String kw) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(tbModel);
        tbPro.setRowSorter(tr);

        if (!"Choose types of beer".equals(kw)) {
            tr.setRowFilter(RowFilter.regexFilter(kw, 3));
        } else {
            tbPro.setRowSorter(tr);
        }
    }

    private void checkOp(JCheckBox ck) {
        String value = ck.getActionCommand();
        if (ck.isSelected()) {
            con.snacks.add(value);
            con.total += 10000;
        }
    }

    private String checkInput() {
        return (cbPro.getSelectedIndex() == 0) ? "" : cbPro.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        mgPro = new javax.swing.JPanel();
        cbNation = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPro = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mgSale = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSale = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cbPro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        rdSquid = new javax.swing.JCheckBox();
        rdPeanuts = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnAddSale = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        intro = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        introText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(0, 153, 153));

        menu.setBackground(new java.awt.Color(0, 102, 102));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        menu.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 212, 160));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCT MANAGEMENT");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 212, 40));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SALE MANAGEMENT");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 212, 40));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INTRODUCTION");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        menu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 212, 40));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LOG OUT");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 212, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cat_Footprint_40px.png"))); // NOI18N
        menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cat_Footprint_40px.png"))); // NOI18N
        menu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 40, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cat_Footprint_40px.png"))); // NOI18N
        menu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 40, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cat_Footprint_40px.png"))); // NOI18N
        menu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Cat_Footprint_40px.png"))); // NOI18N
        menu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 40, 40));

        contentPanel.setBackground(new java.awt.Color(0, 153, 153));
        contentPanel.setLayout(new java.awt.CardLayout());

        mgPro.setBackground(new java.awt.Color(0, 153, 153));

        cbNation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose types of beer", "Viet Nam", "Korean", "Japan", "Thailand", "Germany" }));
        cbNation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNationItemStateChanged(evt);
            }
        });

        tbPro.setBackground(new java.awt.Color(0, 204, 204));
        tbPro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbProMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbPro);

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_15px_2.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDel.setBackground(new java.awt.Color(255, 102, 51));
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_15px_2.png"))); // NOI18N
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCT MANAGEMENT");

        javax.swing.GroupLayout mgProLayout = new javax.swing.GroupLayout(mgPro);
        mgPro.setLayout(mgProLayout);
        mgProLayout.setHorizontalGroup(
            mgProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
            .addGroup(mgProLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbNation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mgProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mgProLayout.setVerticalGroup(
            mgProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mgProLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mgProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );

        contentPanel.add(mgPro, "mgPro");

        mgSale.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SALE MANAGEMENT");

        tbSale.setBackground(new java.awt.Color(0, 204, 204));
        tbSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSaleMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbSale);

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");

        cbPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbProFocusGained(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Snacks:");

        rdSquid.setForeground(new java.awt.Color(0, 0, 0));
        rdSquid.setText("Dried shredded squid");

        rdPeanuts.setForeground(new java.awt.Color(0, 0, 0));
        rdPeanuts.setText("Roasted salted peanuts");

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total:");

        btnAddSale.setBackground(new java.awt.Color(255, 102, 51));
        btnAddSale.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_15px_2.png"))); // NOI18N
        btnAddSale.setText("Add");
        btnAddSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaleActionPerformed(evt);
            }
        });

        btnTest.setBackground(new java.awt.Color(255, 204, 51));
        btnTest.setForeground(new java.awt.Color(102, 102, 102));
        btnTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Plus_15px_2.png"))); // NOI18N
        btnTest.setText("Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_beer_80px.png"))); // NOI18N

        javax.swing.GroupLayout mgSaleLayout = new javax.swing.GroupLayout(mgSale);
        mgSale.setLayout(mgSaleLayout);
        mgSaleLayout.setHorizontalGroup(
            mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mgSaleLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addComponent(jScrollPane2)
            .addGroup(mgSaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mgSaleLayout.createSequentialGroup()
                        .addComponent(cbPro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mgSaleLayout.createSequentialGroup()
                                .addComponent(rdSquid)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addComponent(rdPeanuts))
                        .addGroup(mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mgSaleLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mgSaleLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel12))))
                    .addGroup(mgSaleLayout.createSequentialGroup()
                        .addComponent(btnTest)
                        .addGap(52, 52, 52)
                        .addComponent(btnAddSale)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mgSaleLayout.setVerticalGroup(
            mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mgSaleLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mgSaleLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(rdSquid)
                            .addComponent(jLabel13)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(rdPeanuts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mgSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddSale)
                            .addComponent(btnTest))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mgSaleLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)
                        .addContainerGap())))
        );

        contentPanel.add(mgSale, "mgSale");

        intro.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INTRODUCTION");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/member_1.jpg"))); // NOI18N

        introText.setColumns(20);
        introText.setRows(5);
        introText.setText("The cat (Felis catus) is a domestic species of small carnivorous mammal.[1][2] It is the only domesticated species in the family Felidae and is commonly referred to as the domestic cat \nor house cat to distinguish it from the wild members of the family.[4] Cats are commonly kept as house pets but can also be farm cats or feral cats; the feral cat ranges freely and avoids\n human contact.[5] Domestic cats are valued by humans for companionship and their ability to kill rodents. About 60 cat breeds are recognized by various cat registries.[6] \nThe cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth, and retractable claws adapted to killing small prey like mice and rats.\nIts night vision and sense of smell are well developed. Cat communication includes vocalizations like meowing, purring, trilling, hissing, growling, and grunting as well as cat-specific body language. \nAlthough the cat is a social species, it is a solitary hunter. As a predator, it is crepuscular, i.e. most active at dawn and dusk. It can hear sounds too faint or too high in frequency for human ears, \nsuch as those made by mice and other small mammals.[7] It also secretes and perceives pheromones.[8]\nFemale domestic cats can have kittens from spring to late autumn, with litter sizes often ranging from two to five kittens.[9] Domestic cats are bred and shown at events as registered pedigreed cats, \na hobby known as cat fancy. Population control of cats may be achieved by spaying and neutering, but their proliferation and the abandonment of pets has resulted in large numbers of feral cats worldwide, \ncontributing to the extinction of entire bird, mammal, and reptile species.[10]\nIt was long thought that cat domestication began in ancient Egypt, where cats were venerated from around 3100 BC,[11][12] but recent advances in archaeology and genetics have shown that\ntheir domestication occurred in Western Asia around 7500 BC.[13]\nAs of 2021, there were an estimated 220 million owned and 480 million stray cats in the world.[14][15] As of 2017, the domestic cat was the second most popular pet in the United States, \nwith 95.6 million cats owned[16][17][18] and around 42 million households owning at least one cat.[19] In the United Kingdom, 26% of adults have a cat, with an estimated population of 10.9 million \npet cats as of 2020.[20] The origin of the English word cat, Old English catt, is thought to be the Late Latin word cattus, which was first used at the beginning of the 6th century.[21] It was suggested that cattus is \nderived from an Egyptian precursor of Coptic ϣⲁⲩ šau, 'tomcat', or its feminine form suffixed with -t.[22] The Late Latin word may be derived from another Afro-Asiatic[23] or Nilo-Saharan language.\nThe Nubian word kaddîska 'wildcat' and Nobiin kadīs are possible sources or cognates.[24] The Nubian word may be a loan from Arabic قَطّ‎ qaṭṭ ~ قِطّ qiṭṭ.\nHowever, it is \"equally likely that the forms might derive from an ancient Germanic word, imported into Latin and thence to Greek and to Syriac and Arabic\".[25] The word may be derived from Germanic and \nNorthern European languages, and ultimately be borrowed from Uralic, cf. Northern Sami gáđfi, 'female stoat', and Hungarian hölgy, 'lady, female stoat'; from Proto-Uralic *käďwä, 'female (of a furred animal)'.[26]\nThe English puss, extended as pussy and pussycat, is attested from the 16th century and may have been introduced from Dutch poes or from Low German puuskatte, related to Swedish kattepus, or Norwegian pus,\npusekatt. Similar forms exist in Lithuanian puižė and Irish puisín or puiscín. The etymology of this word is unknown, but it may have arisen from a sound used to attract a cat.[27][28]\nA male cat is called a tom or tomcat[29] (or a gib,[30] if neutered). A female is called a queen[31] (or a molly,[32][user-generated source?] if spayed), especially in a cat-breeding context. A juvenile cat is referred to \nas a kitten. In Early Modern English, the word kitten was interchangeable with the now-obsolete word catling.[33] A group of cats can be referred to as a clowder or a glaring.[34]");
        introText.setEnabled(false);
        jScrollPane3.setViewportView(introText);

        javax.swing.GroupLayout introLayout = new javax.swing.GroupLayout(intro);
        intro.setLayout(introLayout);
        introLayout.setHorizontalGroup(
            introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        introLayout.setVerticalGroup(
            introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(introLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        contentPanel.add(intro, "intro");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want to log out?", "Log out?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            login log = new login();
            log.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void tbProMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProMousePressed
        // TODO add your handling code here:
        con.currentRow = tbPro.getSelectedRow();
        btnDel.setVisible(true);
    }//GEN-LAST:event_tbProMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        cardLayout.show(contentPanel, "mgPro");
        cbNation.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        cardLayout.show(contentPanel, "mgSale");
        int itemCount = cbPro.getItemCount();
        for (int i = 0; i < itemCount; i++) {
            cbPro.removeItemAt(0);
        }
        con.loadcbPro();
        cbPro.setSelectedIndex(0);
        txtTotal.setText("");
        rdSquid.setSelected(false);
        rdPeanuts.setSelected(false);
        cbPro.setBackground(Color.white);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        cardLayout.show(contentPanel, "intro");
    }//GEN-LAST:event_jLabel7MousePressed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int result = JOptionPane.showConfirmDialog(
                this,
                "Do you want delete?", "Delete?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            con.deletePro();
            fillToTable();
            con.saveFilePro();
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void cbNationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNationItemStateChanged
        btnDel.setVisible(false);
        String kw = cbNation.getSelectedItem().toString();
        filter(kw);
    }//GEN-LAST:event_cbNationItemStateChanged

    private void tbSaleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSaleMousePressed
        con.currentRow = tbSale.getSelectedRow();
    }//GEN-LAST:event_tbSaleMousePressed

    private void btnAddSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaleActionPerformed
        con.total = 0;
        con.checkName = checkInput();
        if (!"".equals(con.checkName)) {
            checkOp(rdSquid);
            checkOp(rdPeanuts);
            con.addSale();
            JOptionPane.showMessageDialog(null, "Add successfully");
            fillToTableSale();
        } else {
            cbPro.setBackground(Color.red);
        }
    }//GEN-LAST:event_btnAddSaleActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        con.total = 0;
        con.checkName = checkInput();
        if (!"".equals(con.checkName)) {
            checkOp(rdSquid);
            checkOp(rdPeanuts);
            con.testSale();
            txtTotal.setText(String.valueOf(con.total));
        } else {
            cbPro.setBackground(Color.red);
            txtTotal.setText("");
        }
    }//GEN-LAST:event_btnTestActionPerformed

    private void cbProFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbProFocusGained
        cbPro.setBackground(Color.white);
    }//GEN-LAST:event_cbProFocusGained

    private void tbProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProMouseClicked
        if (evt.getClickCount() == 2) {
            String name = (String) tbPro.getValueAt(con.currentRow, 1);
            addForm.txtName.setText(name);
            int price = (int) tbPro.getValueAt(con.currentRow, 2);
            addForm.txtPrice.setText(String.valueOf(price));
            String nation = (String) tbPro.getValueAt(con.currentRow, 3);
            addForm.cbNation.setSelectedItem(nation);
            String des = (String) tbPro.getValueAt(con.currentRow, 4);
            addForm.txtDes.setText(des);

            addForm.upPro.setVisible(true);
            addForm.savePro.setVisible(false);
            addForm.lbUp.setVisible(true);
            addForm.lbAdd.setVisible(false);

            addForm.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tbProMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSale;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnTest;
    public static javax.swing.JComboBox<String> cbNation;
    public static javax.swing.JComboBox<String> cbPro;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel intro;
    private javax.swing.JTextArea introText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel mgPro;
    private javax.swing.JPanel mgSale;
    private javax.swing.JCheckBox rdPeanuts;
    private javax.swing.JCheckBox rdSquid;
    public static javax.swing.JTable tbPro;
    public static javax.swing.JTable tbSale;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
